FROM fusionauth/fusionauth-app:latest

# Set environment variables
ENV FUSIONAUTH_APP_MEMORY=1024M
ENV FUSIONAUTH_APP_RUNTIME_MODE=production
ENV FUSIONAUTH_APP_URL=http://0.0.0.0:9011

# Expose ports
EXPOSE 9011
