app = "halo-fusionauth"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 9011
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
